// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trabalho;

#nullable disable

namespace academia.Migrations
{
    [DbContext(typeof(BaseAcademia))]
    partial class BaseAcademiaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Trabalho.Academia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomePlano")
                        .HasColumnType("TEXT");

                    b.Property<string>("tipoPlano")
                        .HasColumnType("TEXT");

                    b.Property<double?>("valorPlano")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Academia");
                });

            modelBuilder.Entity("Trabalho.Assinatura", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dataExpirar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int?>("idCliente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("idPlano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nomeCliente")
                        .HasColumnType("TEXT");

                    b.Property<string>("nomePlano")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Assinatura");
                });

            modelBuilder.Entity("Trabalho.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
